### ISSUE TITLE
pygame and fretwork must link to same SDL_mixer

### ISSUE THREAD

**Issue by alvanson** [fofix/fofix#104]
If `pygame` and `fretwork` link to different `SDL_mixer` libraries, creating a `StreamingSound` object will fail with `SDL_mixer is not initialized`. Normally, the mixer is initialized in `GameEngine.__init__()` with the call to `self.audio.open()` (`fretwork.audio.Audio.open()`) which in turn calls `pygame.mixer.init()` which will initialize **`pygame`**'s `SDL_mixer`. However, creation of a `StreamingSound` object calls into `fretwork.mixstream.MixStream` which, if linked to a *different* `SDL_mixer`, fails since this different `SDL_mixer` is not initialized.

It is possible to end up in this situation if using a virtualenv (at least on Linux), as the `pygame` wheel will have its own copy of `SDL_mixer` and `fretwork` will instead link against the system copy as the only option currently is to build from source.

**Comment by BenJuan26** [comment]
This is occurring for me currently on macOS Sierra. Is there a know temporary fix? `pygame` won't open if its own copies of the libs are deleted, so I'm guessing the only solution would be to link `fretwork` to the `pygame` copies. I'm not sure how to do this.

**Comment by Ormin** [comment]
Still occuring on OSX, anyone knows whether this gets fixed?

**Comment by Ormin** [comment]
Ok, managed to fix it for myself.

Did those things:
1) Removed fretwork line from requirements.txt
2) Made sure SDL is present on the system ( brew install sdl probably should do )
3) Installed portmidi, needed for MIDI support in pygame:
brew install portmidi
4) Installed all dependencies except fretwork using pip:
pip install --user --no-binary :all: -r requirements.txt --no-cache-dir
This should compile everything from scratch including pygame to link against SDL in your system
5) Installed fretwork with cmd:
ARCHFLAGS='-arch x86_64' pip install --user --no-binary :all: --no-cache-dir fretwork 

( ARCHFLAGS because sometimes there's a conflict and an -arch i386 flag is added in damaging the build )

At this game python fofix.py should run the game without any problems.

**Comment by Linkid** [comment]
When I packaged fretwork, I used SDL_mixer 1.12.2 (the last version of 1.2.x branch). And it seems like pygame 1.9.3 used the same version of SDL_mixer… So, I don't know why this is not working properly. I'll make an issue in the fretwork repo to remember about it.

But like @Ormin said, to fix it quickly, you need to install ``Cython`` first, then install ``pygame`` and ``fretwork`` by not using their binaries (with the ``--no-binary`` option). This also means that you need all the dependencies to compile them…

**Comment by Ormin** [comment]
@Linkid I thought reason is that pygame - when binary is pulled - is linked against the mixer statically ( I think I saw somewhere a mention it is embedded inside ).. not sure what to think about this issue anymore.

Anyways, at least for now we have a working workaround :)
